exclude: scrape_notifier/migrations/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    - id: mypy
      # additional stubs must be given manually unfortunately:
      # https://github.com/pre-commit/mirrors-mypy/issues/50
      additional_dependencies: [types-toml, types-requests]
      args: [ --check-untyped-defs, --ignore-missing-imports ]
