[telegram]
token = ""

[scraper]
link_template = "https://example.gov/appointments/index.php?office={office_index}"
message_template = "Found free date at {date} for office [{office_name}](https://example.gov/appointments/index.php?office={office_index})\n"
# list of variables to fill templates with
targets = [
    {office_name = "Downtown", office_index = 0},
    {office_name = "West", office_index = 1},
    {office_name = "Sea Point", office_index = 2},
]
# expression matches first occurence and makes captured groups available for later string formating
extraction_regex = '<td class="calendar_available_day">.+year=(\d{4})&day=(\d{1,2})&month=(\d{1,2})'
date_template = '{1:0>2}.{2:0>2}.{0}'
# look for appointments max 30 days in future
max_days_in_future = 30
scrape_interval_seconds = 600
