# fly.toml app configuration file generated for scrape-notifier on 2023-12-29T12:01:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrape-notifier"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[[services]]

[mounts]
source = "sqlite_data"
destination = "/app/data"
