"""rename user id, add joined date

Revision ID: 3d6e419ecf47
Revises: eb3cfcf05206
Create Date: 2022-07-31 10:52:37.915477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d6e419ecf47"
down_revision = "eb3cfcf05206"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "id", new_column_name="telegram_id")
    op.add_column("users", sa.Column("joined", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "telegram_id", new_column_name="id")
    op.drop_column("users", "joined")
    # ### end Alembic commands ###
